services:
  habittracker.api:
    image: ${DOCKER_REGISTRY-}habittrackerapi
    build:
      context: .
      dockerfile: HabitTracker.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://habittracker.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  habittracker.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888